#!/bin/sh  

# A simple utility to start the webserver in a real installation,
# Do not forget to edit to your own needs. This file also works great with 
# crontab for automatic scheduling. 


# Do not forget to change paths! 


if [ $1 = "start" ]; then 
    # Kill the idleserver if it is running 
    pkill -f "python src/idleserver.py" 
    sleep 5

    # Start the lightserver if it is not running 
    if [ $(pgrep -f "python src/lightserver.py" | wc -l) -eq 0 ] ; then 
        cd ~/programmering/playhouse/playhouse-lights/ # This path 
        python src/lightserver.py & 
        sleep 5 
    fi 

    # Start the webserver 
    cd ~/programmering/playhouse/playhouse-web # And this path 
    python src/webserver.py &

elif [ $1 = "stop" ]; then 
    # Stop the webserver 
    pkill --signal sigint -f "python src/webserver.py" 
    sleep 5

    # Start the idle server 
    cd ~/programmering/playhouse/playhouse-web # And this path 
    python src/idleserver.py & 
fi 




